/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string = string> extends Record<string, unknown> {
      StaticRoutes: `/` | `/(modals)/SavedHalls` | `/(modals)/authentication/login` | `/(modals)/authentication/modals/childModal` | `/(modals)/authentication/modals/innerModals/changeNameModal` | `/(modals)/authentication/modals/innerModals/memberModal` | `/(modals)/authentication/modals/mainChatModal` | `/(modals)/authentication/signup` | `/(modals)/authentication/signup_modal` | `/(modals)/authentication/third_party_instance` | `/(modals)/book/components/calendar_strip` | `/(modals)/book/components/filter_modal` | `/(modals)/book/components/order_inside_flatlist` | `/(modals)/book/components/order_separator` | `/(modals)/cameraModal` | `/(modals)/chat/components/filter_modal` | `/(modals)/chat/components/group_chat` | `/(modals)/chat/components/personal_chat` | `/(modals)/chat/util/message_function` | `/(modals)/chat/util/objectID` | `/(modals)/chat/util/time_changing` | `/(modals)/context/CalendarContext` | `/(modals)/context/Languages` | `/(modals)/context/authContext` | `/(modals)/context/errorContext` | `/(modals)/context/savedHall` | `/(modals)/context/store/bookStore` | `/(modals)/context/store/chatStore` | `/(modals)/context/store/friendStore` | `/(modals)/context/store/notificationStore` | `/(modals)/friend/components/friendSeparator` | `/(modals)/friend/components/friend_add` | `/(modals)/friend/util/friend_functions` | `/(modals)/friendReqModal` | `/(modals)/sags` | `/(tabs)` | `/(tabs)/` | `/(tabs)/chat` | `/(tabs)/friend` | `/(tabs)/inbox` | `/(tabs)/order` | `/(tabs)/profile` | `/SavedHalls` | `/_sitemap` | `/authentication/login` | `/authentication/modals/childModal` | `/authentication/modals/innerModals/changeNameModal` | `/authentication/modals/innerModals/memberModal` | `/authentication/modals/mainChatModal` | `/authentication/signup` | `/authentication/signup_modal` | `/authentication/third_party_instance` | `/book/components/calendar_strip` | `/book/components/filter_modal` | `/book/components/order_inside_flatlist` | `/book/components/order_separator` | `/cameraModal` | `/chat` | `/chat/components/filter_modal` | `/chat/components/group_chat` | `/chat/components/personal_chat` | `/chat/util/message_function` | `/chat/util/objectID` | `/chat/util/time_changing` | `/context/CalendarContext` | `/context/Languages` | `/context/authContext` | `/context/errorContext` | `/context/savedHall` | `/context/store/bookStore` | `/context/store/chatStore` | `/context/store/friendStore` | `/context/store/notificationStore` | `/friend` | `/friend/components/friendSeparator` | `/friend/components/friend_add` | `/friend/util/friend_functions` | `/friendReqModal` | `/inbox` | `/listing/book/CallWaveButton` | `/listing/book/modal_calendar` | `/listing/book/support_components/swipe_remove` | `/listing/detail` | `/listing/explore` | `/listing/notification` | `/listing/review/util/inner_zaal_review` | `/listing/review/util/star_rating` | `/order` | `/profile` | `/sags` | `/settings/mainSettings` | `/settings/profileSettings`;
      DynamicRoutes: `/(modals)/chat/${Router.SingleRoutePart<T>}` | `/(modals)/user/${Router.SingleRoutePart<T>}` | `/chat/${Router.SingleRoutePart<T>}` | `/listing/${Router.SingleRoutePart<T>}` | `/listing/book/${Router.SingleRoutePart<T>}` | `/listing/review/${Router.SingleRoutePart<T>}` | `/user/${Router.SingleRoutePart<T>}`;
      DynamicRouteTemplate: `/(modals)/chat/[item]` | `/(modals)/user/[friend_name]` | `/chat/[item]` | `/listing/[sportHallID]` | `/listing/book/[zaal_id]` | `/listing/review/[zaalReview]` | `/user/[friend_name]`;
    }
  }
}
